# Generated by Django 5.2.5 on 2025-09-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0004_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
