# Generated by Django 5.2.5 on 2025-09-02 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
