# Generated by Django 5.2.5 on 2025-09-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_user', '0003_remove_profile_address_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter phone number with country code (e.g., +90 555 123 4567)', max_length=20, null=True),
        ),
    ]
